# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5M8_9Iv8fZtVZFQiiELg-skSiMSbzip
"""

import pandas as pd
data = pd.read_csv("student_performance_dataset.csv", encoding="latin1")
data = pd.read_csv("student_performance_dataset.csv", encoding="latin1", on_bad_lines="skip")

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Load dataset
data = pd.read_csv("student_performance_dataset.csv", encoding="latin1",on_bad_lines="skip")

# Convert column names to lowercase
data.columns = data.columns.str.lower()

# Input features and target
X = data[["study_hours", "attendance", "previous_mark", "assignment_score"]]
y = data["result"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Model evaluation
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Student Performance Risk Classification")
print("Model Accuracy:", round(accuracy * 100, 2), "%")


# Intelligent Feature with Error Handling
def predict_student_risk(study_hours, attendance, previous_mark, assignment_score):

    try:
        # Check values
        values = [study_hours, attendance, previous_mark, assignment_score]

        if any(value < 0 for value in values):
            return "Error: Values cannot be negative."

        if attendance > 100 or previous_mark > 100 or assignment_score > 100:
            return "Error: Marks and attendance must be between 0 and 100."

        # Create input
        student = pd.DataFrame(
            [[study_hours, attendance, previous_mark, assignment_score]],
            columns=[
                "study_hours",
                "attendance",
                "previous_mark",
                "assignment_score"
            ]
        )

        # Prediction
        prediction = model.predict(student)

        return "Prediction: " + str(prediction[0])

    except Exception as e:
        return "Error: Invalid input."


# Example 1 - Valid input
print(predict_student_risk(3, 65, 55, 60))

# Example 2 - Error handling
print(predict_student_risk(3, 120, 55, 60))